In [1]:
import numpy as np
import random

In [2]:
#   Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz 
#       Vektörler tek matrisler çok boyutludur.

In [3]:
#   10 elemanli bir listeden NumPy Array’i olusturunuz.
np.array([1,2,3,4,5,6,7,8,9,10])   

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#   Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.
np.zeros((10,10), dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
#   Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.
np.ones((10,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [6]:
#   Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.
np.full((10,10),9, dtype=int)

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [7]:
#   5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.
np.arange(5,25, 3)

array([ 5,  8, 11, 14, 17, 20, 23])

In [8]:
#   -1 ile 1 arasinda 30 adet Array olusturunuz.
np.linspace(-1,1,30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [9]:
#   0 ile 30 arasinda 5x6’lik bir matris olusturun.
np.random.randint(0,30,(5,6))

array([[18, 19, 13,  8,  4, 17],
       [ 6, 21,  9, 29, 29,  1],
       [16, 28, 27,  5, 21, 18],
       [16, 20, 25,  8, 29, 17],
       [25, 11, 28, 10, 15, 15]])

In [10]:
#   Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.
np.eye(10,dtype="int")

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [11]:
#   0 ile 10 arasinda 5x10’lik bir matris olusturun(integer). 
#   Bu matrisin; 
    # • eleman sayisini 
    # • boyut bilgisini/sayisini 
    # • satir X sutun bilgisini 
    # • veri tipini numpy metodlariyla yazdiriniz.

matris = np.random.randint(0,10,(5,10))
print(matris)
print(f"Eleman sayısı           : {matris.size}\nBoyut sayısı            : {matris.ndim}\nSatir X sutun bilgisini : {matris.shape}\nVeri tipi               : {matris.dtype}")

[[7 2 9 7 0 5 6 8 5 2]
 [1 8 7 5 1 4 0 4 8 5]
 [5 5 6 5 2 0 7 3 9 2]
 [0 1 2 5 2 0 3 3 1 4]
 [2 9 7 7 9 0 5 8 7 8]]
Eleman sayısı           : 50
Boyut sayısı            : 2
Satir X sutun bilgisini : (5, 10)
Veri tipi               : int32


In [12]:
#   0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)
np.random.randint(0,10,(3,4,7))

array([[[6, 9, 8, 5, 9, 2, 9],
        [6, 3, 5, 3, 3, 4, 2],
        [1, 7, 9, 0, 9, 2, 9],
        [8, 1, 2, 0, 5, 0, 2]],

       [[8, 5, 8, 6, 6, 5, 4],
        [3, 8, 0, 2, 6, 9, 4],
        [2, 2, 2, 0, 1, 0, 7],
        [2, 5, 6, 7, 4, 1, 4]],

       [[9, 1, 2, 4, 5, 3, 7],
        [9, 8, 4, 1, 3, 8, 2],
        [8, 7, 9, 0, 8, 8, 4],
        [1, 4, 4, 3, 7, 0, 3]]])

In [13]:
#   Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)
vektor = np.arange(1,10)
matris = vektor.reshape((3,3))
print(f"Vektor: {vektor}\nMatris: {matris} ")

Vektor: [1 2 3 4 5 6 7 8 9]
Matris: [[1 2 3]
 [4 5 6]
 [7 8 9]] 


In [14]:
#    4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.
a1 = np.arange(1,10)
a2 = np.arange(10,20)
a3 = np.arange(20,30)
a4 = np.arange(30,40)
print(f"{a1}\n{a2}\n{a3}\n{a4}")
print(50*"*")
concatenate = np.concatenate([a1,a2,a3,a4])
print(concatenate)

[1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29]
[30 31 32 33 34 35 36 37 38 39]
**************************************************
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [15]:
a1 = np.array([1,10])
a2 = np.array([10,20])
a3 = np.array([20,30])
a4 = np.array([30,40])
print(f"{a1}\n{a2}\n{a3}\n{a4}")
print(50*"*")
concatenate = np.concatenate([a1,a2,a3,a4])
print(concatenate)

[ 1 10]
[10 20]
[20 30]
[30 40]
**************************************************
[ 1 10 10 20 20 30 30 40]


In [16]:
#    2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz.
x1 = np.random.randint(1,10,(4,2))
x2 = np.random.randint(10,20,(4,2))
np.concatenate([x1,x2], axis=1)

array([[ 1,  7, 12, 11],
       [ 8,  4, 16, 12],
       [ 9,  2, 15, 10],
       [ 4,  3, 18, 15]])

In [17]:
#    Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?
#      Satırda işlem yapılacaksa "axis = 0"
#      Sütunda işlem yapılacaksa "axis = 1"

In [18]:
#    Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.
array = np.random.randint(1,10,(3,3))
array1 = np.random.randint(10,20,(3,3))
concatenate = np.concatenate((array,array1), axis=1)
concatenate1 = np.concatenate([array,array1], axis=0)
print(concatenate)
print(concatenate1)


[[ 1  6  8 17 11 13]
 [ 4  7  8 17 14 19]
 [ 1  6  9 13 10 11]]
[[ 1  6  8]
 [ 4  7  8]
 [ 1  6  9]
 [17 11 13]
 [17 14 19]
 [13 10 11]]


In [19]:
#    10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 5 ayri array olusturunuz.
list = [1,2,3,4,5,6,7,8,9,10]
np.split(list,[1,3,4,7])

[array([1]), array([2, 3]), array([4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [20]:
#    Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.
rndom = np.random.randint(1,10,(10))
print(rndom)
print(50*"*")
new_rndom = sorted(rndom, reverse=True)
print(new_rndom)
print(50*"*")
x = 0
for i in new_rndom:
    print(f"{x}. index : {i}")
    x += 1
print(50*"*")


[1 9 7 2 4 2 9 2 4 9]
**************************************************
[9, 9, 9, 7, 4, 4, 2, 2, 2, 1]
**************************************************
0. index : 9
1. index : 9
2. index : 9
3. index : 7
4. index : 4
5. index : 4
6. index : 2
7. index : 2
8. index : 2
9. index : 1
**************************************************


In [21]:
#    20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.
randm = np.random.randint(1,10,(20))
print(50*"*")
print(randm)
print(50*"*")
print(randm[3])
print(50*"*")
print(randm[5])
print(50*"*")
print(randm[7])
print(50*"*")

**************************************************
[2 1 7 7 2 2 5 5 7 9 3 8 9 4 3 3 6 8 4 4]
**************************************************
7
**************************************************
2
**************************************************
5
**************************************************


In [22]:
#    10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.
rand = np.random.randint(1,10,(10))
print(50*"*")
print(rand)
print(50*"*")
print(rand[4])
print(50*"*")
rand[4] = 3
print(rand)
print(50*"*")
print(rand[4])
print(50*"*")

**************************************************
[6 6 2 8 6 2 1 3 8 3]
**************************************************
6
**************************************************
[6 6 2 8 3 2 1 3 8 3]
**************************************************
3
**************************************************


In [26]:
#    “Diagonal Matrix” ve “Trace of Matrix” kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

#       Diagonal Matrix : Bir matriste köşegen dışındaki girişlerin sıfır olduğu matristir.

#       Trace of Matrix : Diagonal Matrixteki değerlerin toplanmıdır.
np.random.randint(1,10,5)

array([4, 5, 1, 6, 7])

In [46]:
#    5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)
x = np.random.randint(1,10,4)
print(50*"*")
diago = np.diag(x)
print(diago)
diagon = diago.diagonal()
print(50*"*")
print(diagon)
print(50*"*")
for i in range(len(diagon)):
    print(f"diago[{i}][{i}]: {diagon[i]}")
print(50*"*")

**************************************************
[[9 0 0 0]
 [0 3 0 0]
 [0 0 3 0]
 [0 0 0 8]]
**************************************************
[9 3 3 8]
**************************************************
diago[0][0]: 9
diago[1][1]: 3
diago[2][2]: 3
diago[3][3]: 8
**************************************************


In [50]:
#    10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.
vektor = np.arange(10,20)
print(vektor)
print(50*"*")
print(vektor[3:])

[10 11 12 13 14 15 16 17 18 19]
**************************************************
[13 14 15 16 17 18 19]


In [64]:
#    10X10 luk bir matris olusturunuz ve ; 
#       • 3.satir ve 5.sutuna ulasiniz. 
#       • 5.sutunun tum satirlarina ulasiniz. 
#       • Tum sutunlarin 2.satirlarina ulasiniz. 
#       • tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz. 
#       • satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz. 
#       • satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz. 
#       • sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz. 
#       • 5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.
matris_24 = np.random.randint(0,30,(10,10))
print(50*"*")
print(matris_24)
print(50*"*")
print(f"3. Satır 5. Sütun: {matris_24[3,5]}")
print(50*"*")
print(f"5.sutunun tum satirlari: {matris_24[:,5]}")
print(50*"*")
print(f"Tüm satırların 2. sütunları: {matris_24[2,:]}")
print(50*"*")
print(f"Tüm sutunların 2 ile 7 arasındaki satırları: {matris_24[2:7,:]}")
print(50*"*")
print(f"satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerler: {matris_24[2:5,3:7]}")




**************************************************
[[29 20  3  7 29 15  8 14 23 22]
 [ 4 18  1  0  2 20  6  3 29 28]
 [27 20  5 16 17 15 15 23 15 29]
 [29  7 27  2  6 23 20 18  6 25]
 [29  0 25 25  8 11  1 24 16  9]
 [ 4 26  5  7 12 13  0 17 24  1]
 [17  3 27 17 14 21  4 18  6  0]
 [24 15  3 18 29  5 25 13 22  2]
 [ 3  9 14 24 26  3  8 20 26  5]
 [ 1 10 20 11  2 11  1 27 17 11]]
**************************************************
3. Satır 5. Sütun: 23
**************************************************
5.sutunun tum satirlari: [15 20 15 23 11 13 21  5  3 11]
**************************************************
Tüm satırların 2. sütunları: [27 20  5 16 17 15 15 23 15 29]
**************************************************
Tüm sutunların 2 ile 7 arasındaki satırları: [[27 20  5 16 17 15 15 23 15 29]
 [29  7 27  2  6 23 20 18  6 25]
 [29  0 25 25  8 11  1 24 16  9]
 [ 4 26  5  7 12 13  0 17 24  1]
 [17  3 27 17 14 21  4 18  6  0]]
**************************************************
satir indexi

In [68]:
# Bir önceki sorunun devamı 
print(50*"*")
print(f"satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerler: {matris_24[5:,:4]}")
print(50*"*")
print(f"sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlari: {matris_24[0:,(3,6,9)]}")
print(50*"*")
matris_24[5, 5] = 1990
print(matris_24[5,5])
print(50*"*")

**************************************************
satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerler: [[ 4 26  5  7]
 [17  3 27 17]
 [24 15  3 18]
 [ 3  9 14 24]
 [ 1 10 20 11]]
**************************************************
sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlari: [[ 7  8 22]
 [ 0  6 28]
 [16 15 29]
 [ 2 20 25]
 [25  1  9]
 [ 7  0  1]
 [17  4  0]
 [18 25  2]
 [24  8  5]
 [11  1 11]]
**************************************************
1990
**************************************************


In [70]:
#    0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;
#      • 20 den buyuk olan kac deger var. 
#      • 30’dan kucuk kac deger var 
#      • icerisinde 33 gecen kac deger var 
#      • olusturulan arrayin tum elemanlarini 5 ile carpin. 
#      • olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.
q_25 = np.arange(0, 50, 5)
print(q_25)
print(50*"*")
print(np.sum(q_25 > 20))
print(50*"*")
print(np.sum(q_25 < 30))
print(50*"*")
print(np.sum(q_25 == 33))
print(50*"*")
print(q_25 * 5)
print(50*"*")
print(q_25%2)
print(50*"*")

[ 0  5 10 15 20 25 30 35 40 45]
**************************************************
5
**************************************************
6
**************************************************
0
**************************************************
[  0  25  50  75 100 125 150 175 200 225]
**************************************************
[0 1 0 1 0 1 0 1 0 1]
**************************************************


In [73]:
#    0 ile 1 arasinda 50 elamanli bir array olusturunuz ve; 
#      • orlamasini aliniz. 
#      • standart sapmasini aliniz. 
#      • varyansini aliniz. 
#      • median’ini aliniz. 
#      • en kucuk degeri bulunuz. 
#      • en buyuk degeri bulunuz. 
aryy_26=np.random.rand(1,50)
print(50*"*")
print(aryy_26)
print(50*"*")
print(aryy_26.mean())
print(50*"*")
print(aryy_26.std())
print(50*"*")
print(aryy_26.var())
print(50*"*")
print(np.median(aryy_26))
print(50*"*")
print(np.min(aryy_26))
print(50*"*")
print(np.max(aryy_26))
print(50*"*")

**************************************************
[[0.02218564 0.88234193 0.4941078  0.92920173 0.59738407 0.99549561
  0.54861861 0.53547883 0.78757232 0.17818423 0.90720092 0.04651266
  0.26253989 0.39369809 0.34736576 0.51600171 0.04347226 0.9266868
  0.48842466 0.18175233 0.89005057 0.85573136 0.32195008 0.6339278
  0.87758566 0.81870011 0.45532538 0.16605074 0.835065   0.43725315
  0.80220855 0.7541727  0.83541377 0.59727464 0.63538617 0.29035007
  0.17178332 0.59142364 0.55721567 0.24829419 0.361966   0.92873056
  0.80643201 0.9347361  0.95084724 0.93211521 0.70532516 0.07450004
  0.36429845 0.95907661]]
**************************************************
0.5775483160548521
**************************************************
0.29362359472386496
**************************************************
0.0862148153785645
**************************************************
0.5943491410171964
**************************************************
0.022185640570103082
****************************

In [11]:
#    Master odev;
#        Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin.
#        Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin.
#        Istenilen matris bulundugunda program dursun
#        ve toplam kac dongunun kuruldugunu, 
#        ne kadar sure icinde buldugunu 
#        ve istenilen matrisi print ile birlikte ekrana yazdiriniz...
#          TAVSİYE: 
#            20 x 20 luk matrisin bulunmasi saatler surebilir. 
#            Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. 
#            Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz
import time
import numpy as np

start_time = time.time()
count = 0

while True:
    count += 1
    matris_1 = np.random.rand(20, 20)
    matris_2 = np.random.rand(20, 20)
    result_matris = (matris_1 - matris_2)

    diago_matris = np.diag(result_matris)

    if (np.all((diago_matris > -0.1) & (diago_matris < 0.1))) == True:
        print(f"Diagonal Matris     : {diago_matris}")
        break

finish_time = time.time()
last_time = start_time - finish_time
print(f"İki matrisin farkı  : {result_matris}")
print(f"Toplam süre         : {last_time}")
print(f"Tekrar sayısı       : {count}")


Diagonal Matris     : [ 0.09560407 -0.07762169 -0.05863357]
İki matrisin farkı  : [[ 0.09560407 -0.3332504   0.08426771]
 [ 0.49536723 -0.07762169  0.30677554]
 [-0.78253556 -0.05217233 -0.05863357]]
Toplam süre         : -0.0047550201416015625
Tekrar sayısı       : 39
